---
title: "APdata_analysisMW"
author: "Maggie Westerland"
date: "`r Sys.Date()`"
output:
  html_document: default
  pdf_document: default
---

dependency load in
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(knitr)
library(gtsummary)
library(skimr)
library(DBI)
library(RSQLite)
library(lubridate)
library(glmnet)
library(ROCR)
setwd('~/Desktop/grad/capstone/code')
```


data load in
```{r, warning=F}
load('~/Desktop/grad/capstone/final_df.Rdata')
```


cleaning
```{r, warning=F}
final_df <- final_df %>% 
  mutate(pre_htn = as.factor(pre_htn)) %>% 
  mutate(gest_age_wks = as.numeric(gest_age_wks)) %>%
  mutate(ob_gravidity = as.character(ob_gravidity)) %>%
  mutate(ob_gravidity = as.factor(ob_gravidity)) %>%
  mutate(ob_parity = as.character(ob_parity)) %>%
  mutate(ob_parity = as.factor(ob_parity)) %>%
  mutate(ob_multiple_births = as.character(ob_multiple_births)) %>%
  mutate(ob_multiple_births = as.factor(ob_multiple_births)) %>%
  mutate(delivery_method = as.character(delivery_method)) %>%
  mutate(delivery_method = as.factor(delivery_method)) %>%
  mutate(ob_gravidity = factor(ob_gravidity, levels = c(1,
                                                        2,
                                                        3,
                                                        4,
                                                        5,
                                                        6,
                                                        7,
                                                        8,
                                                        9,
                                                        10,
                                                        11,
                                                        12,
                                                        13,
                                                        14,
                                                        15,
                                                        16,
                                                        17,
                                                        18))) %>%
  mutate(ob_parity = factor(ob_parity, levels = c(1,
                                                  2,
                                                  3,
                                                  4,
                                                  5,
                                                  6,
                                                  7,
                                                  8,
                                                  9,
                                                  10,
                                                  11,
                                                  12))) %>% 
  mutate(post_htn = as.factor(post_htn), levels(c('no','yes'))) %>% 
  mutate(
    bmi_return = 
      case_when(
        is.na(bmi_return) ~ 'missing',
        bmi_return == 'yes' ~ 'yes',
        bmi_return == 'no' ~ 'no'
      )
  ) %>% 
  mutate(bmi_return = as.factor(bmi_return), levels(c('no', 'yes', 'missing'))) %>% 
  mutate(
    ob_gravidity = 
      case_when(
        ob_gravidity == '1' ~ '1',
        ob_gravidity == '2' ~ '2',
        ob_gravidity == '3' ~ '3',
        ob_gravidity == '4' ~ '4',
        ob_gravidity == '5' ~ '5',
        ob_gravidity == '6' ~ '6',
        ob_gravidity == '7' ~ '7',
        ob_gravidity == '8' ~ '8',
        ob_gravidity == '9' ~ '9',
        ob_gravidity == '10' ~ '10+',
        ob_gravidity == '11' ~ '10+',
        ob_gravidity == '12' ~ '10+',
        ob_gravidity == '13' ~ '10+',
        ob_gravidity == '14' ~ '10+',
        ob_gravidity == '15' ~ '10+',
      )) %>% 
  mutate(
    ob_parity = 
      case_when(
        ob_parity == '1' ~ '1',
        ob_parity == '2' ~ '2',
        ob_parity == '3' ~ '3',
        ob_parity == '4' ~ '4',
        ob_parity == '5' ~ '5',
        ob_parity == '6' ~ '6',
        ob_parity == '7' ~ '7',
        ob_parity == '8' ~ '8',
        ob_parity == '9' ~ '9+',
        ob_parity == '10' ~ '9+',
        ob_parity == '11' ~ '9+',
        ob_parity == '12' ~ '9+'
      ))
  

final_df$post_htn <- relevel(final_df$post_htn, ref = 'no')
final_df$bmi_return <- relevel(final_df$bmi_return, ref = 'no')
final_df$mom_race <- relevel(final_df$mom_race, ref = 'White or Caucasian')
final_df$mom_ethnicity <- relevel(final_df$mom_ethnicity, ref = 'NH')

```


EDA
```{r, warning=F}
eda_table <- final_df %>% 
  select(mom_age_at_del,
         mom_race,
         mom_ethnicity,
         mom_marital_status,
         employment_status,
         preeclampsia,
         pregest_dm,
         gestational_dm,
         placental_abruption,
         gest_age_wks,
         delivery_method,
         ob_gravidity,
         ob_parity,
         ob_multiple_births,
         baby_count,
         mean_pre_bmi,
         mean_post_bmi,
         bmi_return
  ) %>% 
  tbl_summary(
    by = bmi_return,
    missing_text = 'Missing'
  ) %>%
  add_p() %>% 
  modify_header(label = "**Variable**") %>% 
  bold_labels() 

eda_table %>% 
  as_gt() %>%
  gt::gtsave(filename = "eda_table.tex")

```

binom test
```{r, warning=F}
#binom test
table(final_df[final_df$pre_htn != 1,]$post_htn, final_df[final_df$pre_htn != 1,]$bmi_return, useNA = 'always')

table(final_df[final_df$pre_htn != 1,]$post_htn)
table(final_df[final_df$pre_htn != 1,]$bmi_return)
```


unadjusted
```{r, warning=F}
unadjusted_mod <- glm(
  post_htn ~
    bmi_return,
  data = final_df[final_df$pre_htn != 1,],
  family = binomial(link = "logit")
)

summary(unadjusted_mod)
unadjusted_mod_table <- tbl_regression(unadjusted_mod, exponentiate = T) %>% add_global_p()

unadjusted_mod_table %>% 
  as_gt() %>%
  gt::gtsave(filename = "unadjusted_mod_table.tex")
```


adjusted
```{r, warning=F}
unweighted_mod <- glm(
  post_htn ~ 
    bmi_return +
    mom_age_at_del +
    mom_race +
    mom_ethnicity +
    mom_marital_status +
    employment_status +
    preeclampsia +
    pregest_dm +
    gestational_dm +
    placental_abruption +
    gest_age_wks +
    delivery_method +
    ob_gravidity +
    ob_parity +
    ob_multiple_births +
    baby_count +
    mean_pre_bmi,
  data = final_df[final_df$pre_htn != 1,],
  family = binomial(link = "logit")) 

#manual var selection?? add frequencies for bmi/post_htn, add binom prob (binom.test)

summary(unweighted_mod)

unweighted_mod2 <- glm(
  post_htn ~ 
    bmi_return +
    mom_age_at_del +
    mom_race +
    mom_ethnicity +
    mom_marital_status +
    employment_status +
    preeclampsia +
    pregest_dm +
    gestational_dm +
    placental_abruption +
    gest_age_wks +
    delivery_method +
    ob_gravidity +
    ob_parity +
    ob_multiple_births +
    baby_count +
    mean_pre_bmi,
  data = unweighted_mod$model,
  family = binomial(link = "logit")) 

step_unweight2 <- step(unweighted_mod2)
summary(step_unweight2)
log_reg <- tbl_regression(step_unweight2, exponentiate = T) %>% add_global_p()

log_reg %>% 
  as_gt() %>%
  gt::gtsave(filename = "log_reg_table.tex")
```


ROC/AUC
```{r, warning=F}
final_df$predicted <- predict(step_unweight2, newdata = final_df, type="response")

final_df_pred <- final_df[complete.cases(final_df[, c("predicted", "post_htn")]),]

pred <- prediction(final_df_pred$predicted, final_df_pred$post_htn)
perf <- performance(pred, "tpr", "fpr")

auc <- as.numeric(performance(pred, measure = "auc")@y.values)
auc

pdf("roc.pdf")
plot(perf, main="ROC Curve", col="blue", lwd=2, xlim=c(0,1), ylim=c(0,1)) 
abline(0,1, lwd=2, col="gray")
text(0.8, 0.2, paste("AUC = ", round(auc, 2)), cex = 1.2)

dev.off()
```

